### ISSUE TITLE
Compiling of Stripper fails on Ubuntu 14.04.03

### ISSUE THREAD

**Issue by tobiasschweizer** [Ecdosis/standoff#1]
Hi

I am trying to compile the stripper, but the compilation fails. I use Ubuntu 14.04.03 LTS.

When running `make build` in the stripper directory, I am getting the error that `log.h` is not found:

``` bash
/stripper$ make build
"make" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
make[1]: Entering directory `/home/tobi/gitreps/standoff/stripper'
"make"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux-x86/stripper
make[2]: Entering directory `/home/tobi/gitreps/standoff/stripper'
mkdir -p build/Debug/GNU-Linux-x86/src
rm -f "build/Debug/GNU-Linux-x86/src/dest_file.o.d"
gcc    -c -g -DCOMMANDLINE -DMEMWATCH -Iinclude -I../formatter/include -I/usr/lib/jvm/java-7-openjdk-amd64/include -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include/linux -MMD -MP -MF "build/Debug/GNU-Linux-x86/src/dest_file.o.d" -o build/Debug/GNU-Linux-x86/src/dest_file.o src/dest_file.c
src/dest_file.c:14:17: fatal error: log.h: No such file or directory
 #include "log.h"
                 ^
compilation terminated.
make[2]: *** [build/Debug/GNU-Linux-x86/src/dest_file.o] Error 1
make[2]: Leaving directory `/home/tobi/gitreps/standoff/stripper'
make[1]: *** [.build-conf] Error 2
make[1]: Leaving directory `/home/tobi/gitreps/standoff/stripper'
make: *** [.build-impl] Error 2
```

Could you give some information which dependencies have to be met to use your software? What do I have to to do to obtain `log.h`?

Looking at `rebuild.sh`, I can see the following instructions:

``` bash
gcc -DCOMMANDLINE -DHAVE_EXPAT_CONFIG_H -DHAVE_MEMMOVE -Iinclude -O0 -g3 -Wall src/*.c -lm -lexpat -laspell -ltidy -o stripper
```

 So that would be the following libraries:
- math
- expat
- aspell
- tidy

Running this command, I get the following errors

``` bash
/stripper$  gcc -DCOMMANDLINE -DHAVE_EXPAT_CONFIG_H -DHAVE_MEMMOVE -Iinclude -O0 -g3 -Wall src/*.c -lm -lexpat -laspell -ltidy -o stripper
src/dest_file.c:14:17: fatal error: log.h: No such file or directory
 #include "log.h"
                 ^
compilation terminated.
src/stripper.c:27:23: fatal error: tidy/tidy.h: No such file or directory
 #include <tidy/tidy.h>
                       ^
compilation terminated.
src/userdata.c:27:20: fatal error: aspell.h: No such file or directory
 #include "aspell.h"
                    ^
compilation terminated.
```

Strangely, I also get errors for `tidy` and `aspell` although these are installed on my system:
- `tidy --version`: `HTML Tidy for Linux released on 25 March 2009`
- `aspell --version`: `@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.7-20110707)`

**Comment by schmidda** [comment]
I'm not sure if you can use it for that purpose. It's not a standoff markup tool. Standoff properties are unstructured properties applied to text that don't have a hierarchy, even though they can be generated from an XML file.
I've added  a README.md file to the repository. It lists dependencies, including icu which is necessary for support of Unicode. So the offsets of the properties are now in characters not bytes any more. So ŭ has width of "1" not 3.
You can use the rebuild.sh script for building the executable but I usually call it from Java. The commandline form is mostly for testing. The library is generated by the rebuildll.sh script.

**Comment by tobiasschweizer** [comment]
Great!

After you have added `log.c` it compiles and works for me. I did a test using `act1-scene2-F1-stripped.xml`
